# Use an official Python runtime as a base image
FROM python:3.10.11-slim

# Install system dependencies required for OpenCV and its functionalities
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libx11-dev \
    libgtk-3-dev \
    libcanberra-gtk-module \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    #libjasper-dev \
    libdc1394-22-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    ffmpeg \
    python3-dev \
    libopenblas-dev \
    liblapack-dev \
    && rm -rf /var/lib/apt/lists/*
# Set the working directory
WORKDIR /app

COPY requirements.txt .

# Install Python dependencies
RUN pip install -r requirements.txt

# Copy local code into the container
COPY . /app

# Expose the port the app runs on
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]
